# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:6.10

    working_directory: ~/postman

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          command: |
            yarn install
            sudo npm i -g serverless
            
      - run: 
          command: |
            cd services/email-service
            # create prod config file
            touch config.prod.json
            echo '{' >> config.prod.json
            echo '  "region": "us-east-1",' >> config.prod.json
            echo '  "MAILGUN_APIKEY": "'${MAILGUN_APIKEY}'",'>> config.prod.json
            echo '  "MAILGUN_DOMAIN": "'${MAILGUN_DOMAIN}'"'>> config.prod.json
            echo '}' >> config.prod.json
            # deploy
            sls deploy

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      # run tests!
      # - run: yarn test
